version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: wms-db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wms-db
    ports:
      - "3010:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
